### ISSUE TITLE
Image data somehow affected by piping to gulp-metalsmith

### ISSUE THREAD

**Issue by justinhelmer** [jelz/gulp-metalsmith#1]
First of all, thanks for the great tool. It has been a tremendous help and enables some truly graceful workflows.

I ran into an issue where my images were not being copied over to the `build` directory correctly; I narrowed the `pipeline` issue down to `gulp-metalsmith`.

Without knowing any specifics, I can say that both my `.ico` and `.png` files are somehow corrupted. Although copied over, no image viewer is able to display them, including the browser.

For now, I use [gulp-filter](https://github.com/sindresorhus/gulp-filter) to modify and restore the `vinyl` pipe before and after the `gulp-metalsmith` step, but it would be nice if I could avoid that additional step.

Thank you for your time.

**Comment by jelz** [comment]
Hey @justinhelmer ! Thanks for this bug report.

I've just released v0.0.4 (related commit: https://github.com/jelz/gulp-metalsmith/commit/a0e216f30f796d7a8cf4dd388fcb97b7e2e64dbd). Please let me know if it solves the problem.

**Comment by jelz** [comment]
Issue fixed in v0.0.4, closing.
