### ISSUE TITLE
AssertionError: You must pass a working directory path.

### ISSUE THREAD

**Issue by stavros-liaskos** [jelz/gulp-metalsmith#5]
I have a local installation of npm and gulp under ./metalsmith/security/

My striped `gulpfile.js`looks like this:
```javascript
var metalsmith = require('metalsmith'); //also tried require('..'); -> same output
var gulp = require('gulp');
var glob = require('glob');
var path = require('path');

gulp.task('default', function() {
    return gulp.src('../../sourceRepo')
        .pipe(metalsmith())
        .pipe(gulp.dest('../../build'));
});
```
 This throws an ` AssertionError: You must pass a working directory path.` error.

Apparently `require('metasmith') is wrong. What should I add there?

__EDIT:__
I had a typo in the first line:  var Metalsmith -> var metalsmith
This throws "AssertionError: You must pass a working directory path."

**Comment by dominicscimeca** [comment]
What does your full folder structure look like?
Do you have a node_modules directory?
Here is a good starting point for including files in node.

[https://www.bennadel.com/blog/2169-where-does-node-js-and-require-look-for-modules.htm](url)

**Comment by stavros-liaskos** [comment]
My structure looks like:

```
projectRoot/sourceRepo
           /build
           /metalsmith/security/Makefile
                               /gulpfile.js
                               /index.js
                               /node_modules
                               /package.json
```

FIY sourceRepo is a git subtree thus the "funky" structure. Also, metalsmith  AND gulp are working just fine. Only the gulp-metalsmith is not working!

Here is my functional metalsmith index.js (without gulp..) in case it helps:

``` javascript
var Metalsmith = require('metalsmith');
var markdown = require('metalsmith-markdown');
var collections = require('metalsmith-collections');
var handlebars = require('handlebars');
var inplace = require('metalsmith-in-place');
var layouts = require('metalsmith-layouts');

handlebars.registerHelper('link', function (path) {  // syntax: {{{link "docs/guidlenes/"}}}
    var url = handlebars.escapeExpression(path);
    return new handlebars.SafeString(
        "<a href='" + url + "'>" + url + "</a>"
    );
});

Metalsmith(__dirname)
    .metadata({
        title: "etc etc",
        description: "instructions and guidelines",
        url: "https://etc.etc"
    })
    .source('../../sourceRepo')
    .ignore('.*')
    .destination('../../build')
    .clean(true)  // if set to true, empties ../../build before build project
    .use(collections({        // group all blog posts by internally
        docs: 'docs/!*.md'    // adding key 'collections':'posts'
    }))                         // use `collections.posts` in layouts
    .use(inplace({              // generates hrefs
        engine: 'handlebars',
        pattern: '**/*.md'
    }))
     .use(markdown())
    .use(layouts({              // wrap layouts around html
        engine: 'handlebars'    // use the layout engine you like
    }))
    .build(function (err) { if (err) {throw err; }});

```

**Comment by rafaellyra** [comment]
The problem is that you are loading `metalsmith` instead of `gulp-metalsmith`.
Just change:

```
var metalsmith = require('metalsmith');
```

to:

```
var metalsmith = require('gulp-metalsmith');
```

should solve your problem

**Comment by jelz** [comment]
Thank you @rafaellyra for explaining how to fix the issue. I've just added more detailed information about requiring the tool in both:

- [README](https://github.com/jelz/gulp-metalsmith#usage)
- [tutorial's gulpfile.js](https://github.com/jelz/gulp-metalsmith/blob/master/tutorial/gulpfile.js#L7-L21)

Hope it's all clear now for everybody :)
